# Generated by Django 5.2.8 on 2025-11-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_da_oracao', models.CharField(max_length=1000, verbose_name='Texto da Oração')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Oração Principal'), ('COORDENADA', 'Coordenada'), ('SUB_SUBSTANTIVA', 'Subordinada Substantiva'), ('SUB_ADJETIVA', 'Subordinada Adjetiva'), ('SUB_ADVERBIAL', 'Subordinada Adverbial')], default='PRINCIPAL', max_length=20, verbose_name='Tipo de Oração')),
                ('funcao_sintatica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Função Sintática (se subordinada)')),
            ],
            options={
                'verbose_name': 'Oração',
                'verbose_name_plural': 'Orações',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_completo', models.TextField(verbose_name='Texto do Período')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='ComponenteSintatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_componente', models.CharField(choices=[('SUJEITO', 'Sujeito'), ('PREDICADO', 'Predicado'), ('OBJETO_DIRETO', 'Objeto Direto'), ('OBJETO_INDIRETO', 'Objeto Indireto'), ('COMPLEMENTO_NOMINAL', 'Complemento Nominal'), ('ADJUNTO_ADVERBIAL', 'Adjunto Adverbial'), ('ADJUNTO_ADNOMINAL', 'Adjunto Adnominal')], max_length=20, verbose_name='Tipo de Componente')),
                ('texto_do_componente', models.CharField(max_length=500, verbose_name='Texto do Componente')),
                ('oracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='nucleo.oracao')),
            ],
            options={
                'verbose_name': 'Componente Sintático',
                'verbose_name_plural': 'Componentes Sintáticos',
            },
        ),
        migrations.AddField(
            model_name='oracao',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oracoes', to='nucleo.periodo'),
        ),
    ]
